### ISSUE TITLE
NullReferenceException on an empty method body

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Cesium#142]
For example, compiler will crash when compiling this program:
```c
int main()
{
    int unused;
}
```

Here's a quick test checking that:
```csharp
    [Fact]
    public Task FunctionPtrTest1() => DoTest(@"int main()
{
    int unused;
}");
```

And a stacktrace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Mono.Cecil.Cil.CodeWriter.ComputeHeader()
   at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(Stream stream, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(Stream stream)
   at Cesium.CodeGen.Tests.CodeGenTestBase.EmitAssembly(AssemblyContext context) in C:\Projects\Cesium\Cesium.CodeGen.Tests\CodeGenTestBase.cs:line 60
   at Cesium.CodeGen.Tests.CodeGenTestBase.GenerateAssembly(TargetRuntimeDescriptor runtime, String[] sources) in C:\Projects\Cesium\Cesium.CodeGen.Tests\CodeGenTestBase.cs:line 19
   at Cesium.CodeGen.Tests.CodeGenMethodTests.DoTest(String source) in C:\Projects\Cesium\Cesium.CodeGen.Tests\CodeGenMethodTests.cs:line 7
   at Cesium.CodeGen.Tests.CodeGenMethodTests.FunctionPtrTest1() in C:\Projects\Cesium\Cesium.CodeGen.Tests\CodeGenMethodTests.cs:line 220
```

**Comment by impworks** [comment]
This is caused by a faulty definite return analysis in #90.
The method example provided above has no instructions, yet it's not considered empty by `CompoundStatement.HasDefiniteReturn`, so the implicit `ret` is not added and Mono.Cecil generator crashes.
Implementing a better return analysis algorithm appears to have fixed this issue as well.

A fix is implemented in attached pull request.
