### ISSUE TITLE
Subscription access in field does not work.

### ISSUE THREAD

**Issue by kant2002** [ForNeVeR/Cesium#172]
```
typedef struct
{
    int fixedArr[4];
} foo;

int main()
{
    foo x;
    x.fixedArr[3] = 42;
    return x.fixedArr[3];
}
```

**Comment by kant2002** [comment]
Stack trace from integration test
```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '<SyntheticBuffer>fixedArr' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Cesium.CodeGen.Ir.Expressions.LValues.LValueArrayElement.EmitPointerMoveToElement(IDeclarationScope scope) in C:\d\github\Cesium\Cesium.CodeGen\Ir\Expressions\LValues\LValueArrayElement.cs:line 52
   at Cesium.CodeGen.Ir.Expressions.LValues.LValueArrayElement.EmitSetValue(IDeclarationScope scope, IExpression value) in C:\d\github\Cesium\Cesium.CodeGen\Ir\Expressions\LValues\LValueArrayElement.cs:line 34
   at Cesium.CodeGen.Ir.Expressions.AssignmentExpression.EmitTo(IDeclarationScope scope) in C:\d\github\Cesium\Cesium.CodeGen\Ir\Expressions\AssignmentExpression.cs:line 47
   at Cesium.CodeGen.Ir.BlockItems.ExpressionStatement.EmitTo(IDeclarationScope scope) in C:\d\github\Cesium\Cesium.CodeGen\Ir\BlockItems\ExpressionStatement.cs:line 20
   at Cesium.CodeGen.Ir.BlockItems.CompoundStatement.EmitTo(IDeclarationScope scope) in C:\d\github\Cesium\Cesium.CodeGen\Ir\BlockItems\CompoundStatement.cs:line 28
   at Cesium.CodeGen.Ir.TopLevel.FunctionDefinition.EmitCode(TranslationUnitContext context, FunctionScope scope) in C:\d\github\Cesium\Cesium.CodeGen\Ir\TopLevel\FunctionDefinition.cs:line 227
   at Cesium.CodeGen.Ir.TopLevel.FunctionDefinition.EmitTo(TranslationUnitContext context) in C:\d\github\Cesium\Cesium.CodeGen\Ir\TopLevel\FunctionDefinition.cs:line 86
   at Cesium.CodeGen.Contexts.AssemblyContext.EmitTranslationUnit(IEnumerable`1 nodes) in C:\d\github\Cesium\Cesium.CodeGen\Contexts\AssemblyContext.cs:line 53
   at Cesium.Compiler.Compilation.GenerateCode(AssemblyContext context, String inputFilePath) in C:\d\github\Cesium\Cesium.Compiler\Compilation.cs:line 107
   at Cesium.Compiler.Compilation.GenerateCode(AssemblyContext context, String inputFilePath) in C:\d\github\Cesium\Cesium.Compiler\Compilation.cs:line 107
   at Cesium.Compiler.Compilation.Compile(IEnumerable`1 inputFilePaths, String outputFilePath, TargetRuntimeDescriptor targetRuntime, Nullable`1 moduleKind, String namespace, String globalClassFQN) in C:\d\github\Cesium\Cesium.Compiler\Compilation.cs:line 29
   at Program.<>c.<<<Main>$>b__0_2>d.MoveNext() in C:\d\github\Cesium\Cesium.Compiler\Main.cs:line 29
```
