### ISSUE TITLE
Getting address of function is not supported

### ISSUE THREAD

**Issue by kant2002** [ForNeVeR/Cesium#181]
```c
int foo(int t)
{
    return t + 2;
}

typedef int (*foo_t)(int x);

int main(void)
{
    foo_t x = &foo;
    return x(40);
}
```
produce
```
Unhandled exception. System.NotSupportedException: Cannot find variable foo.
   at Cesium.CodeGen.Ir.Expressions.IdentifierExpression.Resolve(IDeclarationScope scope) in C:\d\github\Cesium\Cesium.CodeGen\Ir\Expressions\IdentifierExpression.cs:line 42
   at Cesium.CodeGen.Ir.Expressions.UnaryOperatorExpression.<EmitTo>g__EmitGetAddress|5_1(IDeclarationScope scope, IExpression target) in C:\d\github\Cesium\Cesium.CodeGen\Ir\Expressions\UnaryOperatorExpression.cs:line 54
   at Cesium.CodeGen.Ir.Expressions.UnaryOperatorExpression.EmitTo(IDeclarationScope scope) in C:\d\github\Cesium\Cesium.CodeGen\Ir\Expressions\UnaryOperatorExpression.cs:line 34
   at Cesium.CodeGen.Ir.BlockItems.DeclarationBlockItem.EmitScopedIdentifier(IDeclarationScope scope, ScopedIdentifierDeclaration scopedDeclaration) in C:\d\github\Cesium\Cesium.CodeGen\Ir\BlockItems\DeclarationBlockItem.cs:line 90
   at Cesium.CodeGen.Ir.BlockItems.DeclarationBlockItem.EmitTo(IDeclarationScope scope) in C:\d\github\Cesium\Cesium.CodeGen\Ir\BlockItems\DeclarationBlockItem.cs:line 50
   at Cesium.CodeGen.Ir.BlockItems.CompoundStatement.EmitTo(IDeclarationScope scope) in C:\d\github\Cesium\Cesium.CodeGen\Ir\BlockItems\CompoundStatement.cs:line 28
   at Cesium.CodeGen.Ir.TopLevel.FunctionDefinition.EmitCode(TranslationUnitContext context, FunctionScope scope) in C:\d\github\Cesium\Cesium.CodeGen\Ir\TopLevel\FunctionDefinition.cs:line 229
   at Cesium.CodeGen.Ir.TopLevel.FunctionDefinition.EmitTo(TranslationUnitContext context) in C:\d\github\Cesium\Cesium.CodeGen\Ir\TopLevel\FunctionDefinition.cs:line 87
   at Cesium.CodeGen.Contexts.AssemblyContext.EmitTranslationUnit(IEnumerable`1 nodes) in C:\d\github\Cesium\Cesium.CodeGen\Contexts\AssemblyContext.cs:line 49
   at Cesium.Compiler.Compilation.GenerateCode(AssemblyContext context, String inputFilePath) in C:\d\github\Cesium\Cesium.Compiler\Compilation.cs:line 107
   at Cesium.Compiler.Compilation.GenerateCode(AssemblyContext context, String inputFilePath) in C:\d\github\Cesium\Cesium.Compiler\Compilation.cs:line 107
   at Cesium.Compiler.Compilation.Compile(IEnumerable`1 inputFilePaths, String outputFilePath, TargetRuntimeDescriptor targetRuntime, Nullable`1 moduleKind, String namespace, String globalClassFQN) in C:\d\github\Cesium\Cesium.Compiler\Compilation.cs:line 29
```

**Comment by kant2002** [comment]
Isn't this indication that we should treat function as variables with function ptr type?

**Comment by ForNeVeR** [comment]
I don't think that we should treat them as _variables_ technically. But it should be possible to extract them from a scope, yes.

**Comment by kant2002** [comment]
I look closely at code and current abstraction `FunctionInfo` is fine for me, it is not Cecil, so not big deal. Faster way to solve probable would be change resolution here
https://github.com/ForNeVeR/Cesium/blob/68df12f319fc1bdcef023cc5525cd9b8dd0f2e3d/Cesium.CodeGen/Ir/Expressions/IdentifierExpression.cs#L32

**Comment by ForNeVeR** [comment]
I think this will work for starters.
