### ISSUE TITLE
Failure during compiling arithmetics.c on Linux

### ISSUE THREAD

**Issue by kant2002** [ForNeVeR/Cesium#37]
```
$ pwsh -c ./Cesium.IntegrationTests/Run-Tests.ps1 -NoBuild
Running tests for 2 cases.
Compiline ~/Cesium/Cesium.IntegrationTests/arithmetics.c with gcc.
Compiling ~/Cesium/Cesium.IntegrationTests/arithmetics.c with Cesium.
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Yoakke.Parser.ParseError' to type 'Yoakke.Parser.ParseOk`1[Cesium.Ast.TranslationUnit]'.
   at Yoakke.Parser.ParseResult`1.get_Ok()
   at Program.<>c.<<Main>$>b__0_0(Arguments args) in ~/Cesium/Cesium.Compiler/Program.cs:line 21
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at Program.<Main>$(String[] args) in ~/Cesium/Cesium.Compiler/Program.cs:line 13
Error: Cesium.Compiler returned exit code 134.
```

**Comment by kant2002** [comment]
Strange, but after recompiling issue disappear. I will keep an eye on it.

**Comment by ForNeVeR** [comment]
I thought about better error reporting, but I see you've already created a PR for this :)
