### ISSUE TITLE
String literal concatenation failing to compile

### ISSUE THREAD

**Issue by abrahamFerga** [ForNeVeR/Cesium#446]
The following code can be run in gcc version 6.3.0, but it is failing to compile with the current version of Cesium

```
#include <stdio.h>
int main() {
    const char *a = "Args: " "1, 2, 3" "\n";
    puts(a);
    return 0;
}
```

That code produces the next error:

Cesium.Core.ParseException
  HResult=0x80131500
  Message=Excessive output after the end of a translation unit Cesium.Samples/test.c at line 17, column 39. Next token int.
  Source=Cesium.Compiler
  StackTrace:
   at Cesium.Compiler.Compilation.<GenerateCode>d__4.MoveNext() in \Cesium\Cesium.Compiler\Compilation.cs:line 120
   at Cesium.Compiler.Compilation.<Compile>d__0.MoveNext() in\Cesium\Cesium.Compiler\Compilation.cs:line 40
   at Program.<>c.<<<Main>$>b__0_0>d.MoveNext() in \Cesium\Cesium.Compiler\Main.cs:line 39
   at Cesium.Compiler.CommandLineParser.<>c__DisplayClass0_0.<<ParseCommandLineArgs>b__1>d.MoveNext() in \Cesium\Cesium.Compiler\CommandLineParser.cs:line 37
   at Cesium.Compiler.CommandLineParser.<ParseCommandLineArgs>d__0.MoveNext() in \Cesium\Cesium.Compiler\CommandLineParser.cs:line 18
   at Program.<<Main>$>d__0.MoveNext() in \Cesium\Cesium.Compiler\Main.cs:line 6

It throws a different exception using the code:
```
int main() {
    const char *a = "Args: " "1, 2, 3" "\n";
    return 0;
}
```

Cesium.Core.ParseException
  HResult=0x80131500
  Message=Error during parsing Cesium.Samples/macro.c. Error at position line 4, column 30. Got "1, 2, 3".
  Source=Cesium.Compiler
  StackTrace:
   at Cesium.Compiler.Compilation.<GenerateCode>d__4.MoveNext() in \Cesium\Cesium.Compiler\Compilation.cs:line 106
   at Cesium.Compiler.Compilation.<Compile>d__0.MoveNext() in \Cesium\Cesium.Compiler\Compilation.cs:line 40
   at Program.<>c.<<<Main>$>b__0_0>d.MoveNext() in \Cesium\Cesium.Compiler\Main.cs:line 39
   at Cesium.Compiler.CommandLineParser.<>c__DisplayClass0_0.<<ParseCommandLineArgs>b__1>d.MoveNext() in \Cesium\Cesium.Compiler\CommandLineParser.cs:line 37
   at Cesium.Compiler.CommandLineParser.<ParseCommandLineArgs>d__0.MoveNext() in \Cesium\Cesium.Compiler\CommandLineParser.cs:line 18
   at Program.<<Main>$>d__0.MoveNext() in \Cesium\Cesium.Compiler\Main.cs:line 6

I am not sure if they are related, or they are even errors with C17.

Environment
OS: Windows 11 Pro
.NET version: 7.0.401
Cesium version: Latest version in main, commit 720b4cbb3f218d535f059d8ca7df28f3392b4057

**Comment by ForNeVeR** [comment]
Thanks for reporting. This concatenation is not supported, yet. Of course we should support it.

**Comment by kant2002** [comment]
@abrahamFerga Are you have appetite to modify parser and IR to handle that scenario?

**Comment by abrahamFerga** [comment]
Sure I can, I am working on another issue, I can work on this one afterwards.
