### ISSUE TITLE
Exception on CI

### ISSUE THREAD

**Issue by kant2002** [ForNeVeR/Cesium#695]
I hit followin exception in CI on my fork's main branch
https://developercommunity.visualstudio.com/t/Parallelly-invoking-MicrosoftVisualStud/10752944?sort=active&topics=enterprise-2017

**Comment by kant2002** [comment]
```
  09:43:39 [ERR] [xUnit.net 00:00:07.00]     Cesium.CodeGen.Tests.CodeGenNetInteropTests.VoidPtrInterop(architecture: Dynamic) [FAIL]
  09:43:40 [DBG]   Failed Cesium.CodeGen.Tests.CodeGenNetInteropTests.VoidPtrInterop(architecture: Dynamic) [4 s]
  09:43:40 [DBG]   Error Message:
  09:43:40 [DBG]    Assert.True() Failure
  09:43:40 [DBG] Expected: True
  09:43:40 [DBG] Actual:   False
  09:43:40 [DBG]   Stack Trace:
  09:43:40 [DBG]      at Cesium.TestFramework.ExecUtil.RunToSuccess(ITestOutputHelper output, String executable, String workingDirectory, String[] args, IReadOnlyDictionary`2 additionalEnvironment) in D:\a\Cesium\Cesium\Cesium.TestFramework\ExecUtil.cs:line 16
  09:43:40 [DBG]    at Cesium.TestFramework.CSharpCompilationUtil.CreateCSharpProject(ITestOutputHelper output, String directory) in D:\a\Cesium\Cesium\Cesium.TestFramework\CSharpCompilationUtil.cs:line 43
  09:43:40 [DBG]    at Cesium.TestFramework.CSharpCompilationUtil.CompileCSharpAssembly(ITestOutputHelper output, TargetRuntimeDescriptor runtime, String cSharpSource) in D:\a\Cesium\Cesium\Cesium.TestFramework\CSharpCompilationUtil.cs:line 34
  09:43:40 [DBG]    at Cesium.CodeGen.Tests.CodeGenNetInteropTests.DoTest(TargetArchitectureSet architecture, String cSharpCode, String cCode) in D:\a\Cesium\Cesium\Cesium.CodeGen.Tests\CodeGenNetInteropTests.cs:line 22
  09:43:40 [DBG] --- End of stack trace from previous location ---
  09:43:40 [DBG]   Standard Output Messages:
  09:43:40 [DBG]  $ dotnet new classlib --framework net8.0 --output TestProject
  09:43:40 [DBG]  
  09:43:40 [DBG]  [ERR] Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  09:43:40 [DBG]  [ERR] Repeat 2 times:
  09:43:40 [DBG]  [ERR] --------------------------------
  09:43:40 [DBG]  [ERR]    at Microsoft.VisualStudio.Setup.Configuration.IEnumSetupInstances.Next(Int32, Microsoft.VisualStudio.Setup.Configuration.ISetupInstance[], Int32 ByRef)
  09:43:40 [DBG]  [ERR] --------------------------------
  09:43:40 [DBG]  [ERR]    at Microsoft.DotNet.Workloads.Workload.VisualStudioWorkloads.GetVisualStudioInstances()
  09:43:40 [DBG]  [ERR]    at Microsoft.DotNet.Workloads.Workload.VisualStudioWorkloads.GetInstalledWorkloads(Microsoft.NET.Sdk.WorkloadManifestReader.IWorkloadResolver, Microsoft.DotNet.Workloads.Workload.List.InstalledWorkloadsCollection, System.Nullable`1<Microsoft.NET.Sdk.WorkloadManifestReader.SdkFeatureBand>)
  09:43:40 [DBG]  [ERR]    at Microsoft.DotNet.Workloads.Workload.List.WorkloadInfoHelper.AddInstalledVsWorkloads(System.Collections.Generic.IEnumerable`1<Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadId>)
  09:43:40 [DBG]  [ERR]    at Microsoft.DotNet.Workloads.Workload.List.WorkloadInfoHelper.get_InstalledAndExtendedWorkloads()
  09:43:40 [DBG]  [ERR]    at Microsoft.DotNet.Tools.New.WorkloadsInfoProvider.GetInstalledWorkloadsAsync(System.Threading.CancellationToken)
  09:43:40 [DBG]  [ERR]    at Microsoft.TemplateEngine.Edge.Constraints.WorkloadConstraintFactory+WorkloadConstraint+<ExtractWorkloadInfoAsync>d__9.MoveNext()
  09:43:40 [DBG]  [ERR]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.TemplateEngine.Edge.Constraints.WorkloadConstraintFactory+WorkloadConstraint+<ExtractWorkloadInfoAsync>d__9, Microsoft.TemplateEngine.Edge, Version=8.0.403.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ExtractWorkloadInfoAsync>d__9 ByRef)
  09:43:40 [DBG]  [ERR]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.TemplateEngine.Edge.Constraints.WorkloadConstraintFactory+WorkloadConstraint+<ExtractWorkloadInfoAsync>d__9, Microsoft.TemplateEngine.Edge, Version=8.0.403.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ExtractWorkloadInfoAsync>d__9 ByRef)
  09:43:40 [DBG]  [ERR]    at Microsoft.TemplateEngine.Edge.Constraints.WorkloadConstraintFactory+WorkloadConstraint.ExtractWorkloadInfoAsync(System.Collections.Generic.IEnumerable`1<Microsoft.TemplateEngine.Abstractions.Components.IWorkloadsInfoProvider>, Microsoft.Extensions.Logging.ILogger, System.Threading.CancellationToken)
  09:43:40 [DBG]  [ERR]    at Microsoft.TemplateEngine.Edge.Constraints.WorkloadConstraintFactory+WorkloadConstraint+<CreateAsync>d__6.MoveNext()
  09:43:40 [DBG]  [ERR]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.TemplateEngine.Edge.Constraints.WorkloadConstraintFactory+WorkloadConstraint+<CreateAsync>d__6, Microsoft.TemplateEngine.Edge, Version=8.0.403.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<CreateAsync>d__6 ByRef)
  09:43:40 [DBG]  [ERR]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.TemplateEngine.Edge.Constraints.WorkloadConstraintFactory+WorkloadConstraint+<CreateAsync>d__6, Microsoft.TemplateEngine.Edge, Version=8.0.403.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<CreateAsync>d__6 ByRef)
  09:43:40 [DBG]  [ERR]    at Microsoft.TemplateEngine.Edge.Constraints.WorkloadConstraintFactory+WorkloadConstraint.CreateAsync(Microsoft.TemplateEngine.Abstractions.IEngineEnvironmentSettings, Microsoft.TemplateEngine.Abstractions.Constraints.ITemplateConstraintFactory, System.Threading.CancellationToken)
  09:43:40 [DBG]  [ERR]    at Microsoft.TemplateEngine.Edge.Constraints.WorkloadConstraintFactory+<Microsoft-TemplateEngine-Abstractions-Constraints-ITemplateConstraintFactory-CreateTemplateConstraintAsync>d__5.MoveNext()
  09:43:40 [DBG]  [ERR]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.TemplateEngine.Edge.Constraints.WorkloadConstraintFactory+<Microsoft-TemplateEngine-Abstractions-Constraints-ITemplateConstraintFactory-CreateTemplateConstraintAsync>d__5, Microsoft.TemplateEngine.Edge, Version=8.0.403.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<Microsoft-TemplateEngine-Abstractions-Constraints-ITemplateConstraintFactory-CreateTemplateConstraintAsync>d__5 ByRef)
  09:43:40 [DBG]  [ERR]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.TemplateEngine.Edge.Constraints.WorkloadConstraintFactory+<Microsoft-TemplateEngine-Abstractions-Constraints-ITemplateConstraintFactory-CreateTemplateConstraintAsync>d__5, Microsoft.TemplateEngine.Edge, Version=8.0.403.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<Microsoft-TemplateEngine-Abstractions-Constraints-ITemplateConstraintFactory-CreateTemplateConstraintAsync>d__5 ByRef)
  09:43:40 [DBG]  [ERR]    at Microsoft.TemplateEngine.Edge.Constraints.WorkloadConstraintFactory.Microsoft.TemplateEngine.Abstractions.Constraints.ITemplateConstraintFactory.CreateTemplateConstraintAsync(Microsoft.TemplateEngine.Abstractions.IEngineEnvironmentSettings, System.Threading.CancellationToken)
  09:43:40 [DBG]  [ERR]    at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
  09:43:40 [DBG]  [ERR]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
  09:43:40 [DBG]  [ERR]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
  09:43:40 [DBG]  [ERR]    at System.Threading.ThreadPoolWorkQueue.Dispatch()
  09:43:40 [DBG]  [ERR]    at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
  09:43:40 [DBG]  [ERR] 

```

**Comment by ForNeVeR** [comment]
Could be the same as #674?
